name: feature_settings
version: 0.0.1
publish_to: 'none'
resolution: workspace

environment:
  sdk: '^3.9.2'
  flutter: ">=3.22.0"

dependencies:
  core_foundation:
    path: ../../core/core_foundation
  feature_dashboard:
    path: ../feature_dashboard
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  get_it: ^8.0.0
  go_router: ^16.2.1
  provider: ^6.1.2

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  freezed: ^2.5.4
