name: core_storage
description: Storage abstractions (secure storage, cache) for the monorepo.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.0.0
