# l10n.yaml
# Configuration for Flutter's internationalization code generation

arb-dir: l10n

template-arb-file: app_en.arb

# Since synthetic-package is deprecated, this must be false.
# Generated Dart files will go into output-dir if specified,
# otherwise into the arb-dir.
synthetic-package: false

# Specify where to output the generated localization files:
output-dir: generated/l10n

# The class name for the generated localization delegate:
output-class: AppLocalizations

# Optional: define locales in preferred order:
preferred-supported-locales:
  - en
  - es

# Whether getters return nullable strings:
nullable-getter: false

# Optional: uncomment if you want to add a header to generated files,
# and make sure header.txt lives inside arb-dir (lib/l10n).
# Either one of these (not both):
# header: |
#   /// Localization for MVVM Flutter Demo.
# header-file: header.txt

# Flutter web option for deferred loading (if needed)
use-deferred-loading: false
