# pubspec.yaml

name: mvvm_flutter_demo
description: A MVVM Flutter demo with i18n, a11y, theming, and white-label support

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  accessibility_tools: ^2.2.0
  core_design_system:
    path: packages/core/core_design_system
  core_analytics:
    path: packages/core/core_analytics
  core_accessibility:
    path: packages/core/core_accessibility
  core_networking:
    path: packages/core/core_networking
  core_storage:
    path: packages/core/core_storage
  core_foundation:
    path: packages/core/core_foundation
  feature_dashboard:
    path: packages/features/feature_dashboard
  feature_products:
    path: packages/features/feature_products
  feature_details:
    path: packages/features/feature_details
  feature_settings:
    path: packages/features/feature_settings
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  flutter_tts: ^4.2.0
  freezed_annotation: ^2.4.4
  get_it: ^8.0.0
  go_router: ^16.2.1
  json_annotation: ^4.9.0
  path_provider: ^2.1.5
  provider: ^6.1.2
  shared_auth:
    path: packages/shared/shared_auth
  shared_configuration:
    path: packages/shared/shared_configuration
  shared_navigation:
    path: packages/shared/shared_navigation
  shared_preferences: ^2.3.3
  shared_user:
    path: packages/shared/shared_user

dev_dependencies:
  # Code generation for internationalization and JSON serialization
  build_runner: ^2.4.13

  # Linting rules - Keep updated for best practices
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  
  # Code generation for Freezed
  freezed: ^2.5.4
  json_serializable: ^6.8.0
  melos: ^7.1.0
  very_good_analysis: ^6.0.0

# Melos v7 workspace definition and scripts
workspace:
  - packages/core/core_design_system
  - packages/core/core_networking
  - packages/core/core_storage
  - packages/core/core_foundation
  - packages/features/feature_dashboard
  - packages/features/feature_products
  - packages/features/feature_details
  - packages/features/feature_settings
  - packages/shared/shared_auth
  - packages/shared/shared_user
  - packages/shared/shared_configuration
  - packages/shared/shared_navigation
  - apps/consumer_app

melos:
  scripts:
    analyze:all:
      description: Run static analysis across all packages
      run: flutter analyze
    format:all:
      description: Format code across all packages
      run: dart format --set-exit-if-changed .
    test:all:
      description: Run tests across all packages
      run: flutter test
    generate:all:
      description: Run build_runner in all packages that depend on it
      run: melos exec --depends-on build_runner -- flutter packages pub run build_runner build --delete-conflicting-outputs
    generate:app:
      description: Run build_runner in the application (root) package
      run: dart run build_runner build --delete-conflicting-outputs
    clean:all:
      description: Clean all packages
      run: flutter clean

# Configuration for internationalization
flutter:
  uses-material-design: true
  
  # Enable generation of localization files
  generate: true
  
  # Asset configuration for white-labeling
  assets:
    - assets/images/
    - assets/brand/
    - assets/config/
    
  # Font configuration for theming
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       # - asset: assets/fonts/CustomFont-Regular.ttf
  #       # - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700