name: consumer_app
publish_to: none
description: Consumer application that composes feature packages
version: 0.1.0
resolution: workspace

environment:
  sdk: ^3.8.0
  flutter: ">=3.22.0"

dependencies:
  core_design_system:
    path: ../../packages/core/core_design_system
  core_foundation:
    path: ../../packages/core/core_foundation
  core_localization:
    path: ../../packages/core/core_localization
  core_networking:
    path: ../../packages/core/core_networking
  core_storage:
    path: ../../packages/core/core_storage
  feature_dashboard:
    path: ../../packages/features/feature_dashboard
  feature_details:
    path: ../../packages/features/feature_details
  feature_products:
    path: ../../packages/features/feature_products
  feature_settings:
    path: ../../packages/features/feature_settings
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.0
  go_router: ^16.2.1
  mvvm_flutter_demo:
    path: ../..
  provider: ^6.1.2
  shared_auth:
    path: ../../packages/shared/shared_auth
  shared_configuration:
    path: ../../packages/shared/shared_configuration
  shared_navigation:
    path: ../../packages/shared/shared_navigation
  shared_user:
    path: ../../packages/shared/shared_user

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
