name: feature_products
description: Products feature package (domain, application, and presentation layers).
version: 0.0.1
publish_to: 'none'
resolution: workspace

environment:
  sdk: '^3.9.2'
  flutter: ">=3.22.0"

dependencies:
  core_foundation:
    path: ../../core/core_foundation
  core_localization:
    path: ../../core/core_localization
  flutter:
    sdk: flutter
  get_it: ^8.0.0
  go_router: ^16.2.1
  # Add feature-specific deps as needed (e.g., shared_user, core_design_system)

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
