name: shared_navigation
description: Shared navigation abstractions and models for app-wide routing.
version: 0.0.1
publish_to: 'none'
resolution: workspace

environment:
  sdk: '^3.9.2'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
