name: core_configuration
version: 0.1.0
publish_to: 'none'
description: Core configuration models and service (AppConfig, ConfigService) for the monorepo.
homepage: https://example.com
resolution: workspace

environment:
  sdk: '^3.9.2'
  flutter: '>=3.22.0'

dependencies:
  core_foundation:
    path: ../core_foundation
  core_storage:
    path: ../core_storage
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  path_provider: ^2.1.3
  shared_preferences: ^2.3.3

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  very_good_analysis: ^6.0.0

