name: core_foundation
description: Foundational core types shared across features (Result, UseCase, Failures, ErrorMapper, base ViewModel, Logger, PerformanceMonitor).
version: 0.0.1
publish_to: 'none'
resolution: workspace

environment:
  sdk: '^3.9.2'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
